"""
Neovim rplugin manifest for nvim-nomadnet.

Register this plugin by adding this file as one of the following:
  1. ~/.config/nvim/rplugin.vim
  2. ~/.local/share/nvim/rplugin.vim
  3. plugin/nvim-nomadnet.vim (which calls remote#host#RegisterPlugin)

The @pynvim.plugin decorators in nva.py handle registration automatically
when pynvim processes the file.
"""

# The rplugin manifest is auto-generated by pynvim when loading the
# plugin file. The file is registered via:
#   :UpdateRemotePlugins
# after placing nva.py where Neovim can find it.

# Recommended placement:
#   ln -s ~/src/NomadNet/nvim-nomadnet/python/nva.py \
#         ~/.config/nvim/rplugin/python3/nva.py
# Then run:
#   :UpdateRemotePlugins
# Restart Neovim.
